### ISSUE TITLE
docker-compose - invalid string

### ISSUE THREAD

**Issue by angry-bender** [mammo0/docker-arkime#23]
**Issue**
When using the docker compose and env files from a git clone of this repo, docker compose up -d returns the following error:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.arkime.env_file contains {"path": "./env/arkime-compose.env"}, which is an invalid type, it should be a string
```

**Expected Behavior**
the docker compose file would read the env file (Noting no customisations have been made)

**Workaround**
Removing the yaml sections for `services.arkime.env_file` completely allows the compose to work, but no custom env vars would work. (Unless specified in the compose file)

**Comment by angry-bender** [comment]
Found the issue, this version of docker seems to want a full path, could be worth adding to the README

**Comment by mammo0** [comment]
Hello and sorry for the late reply...

What Docker Compose Version did you use?
According to the docs the `required` attribute requires at least version 2.24.0 (https://docs.docker.com/reference/compose-file/services/#env_file)

**Comment by angry-bender** [comment]
All good, thanks for the reminder. Your bang on, I was using a old docker-compose version.
